version: '3'

services:
  app:
    container_name: react-app-im8
    build: .
    entrypoint: ./.docker/entrypoint.sh
    ports: 
      - 3001:3000
    volumes:
      - .:/home/react/app
    environment:
      WDS_SOCKET_HOST: "127.0.0.1"
      # CHOKIDAR_USEPOLLING: "true"
  
  